# .github/workflows/windows_release.yml

name: Build & Release Windows App (Portable)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      # --- MODIFIED STEP ---
      # Added --verbose to see all build logs
      - name: Build Windows
        run: flutter build windows --release --verbose

      # --- MODIFIED DEBUGGING STEP ---
      # This will list folders to see what was created
      - name: List build directory contents
        run: |
          echo "--- Listing contents of build ---"
          Get-ChildItem -Path build -ErrorAction SilentlyContinue
          echo "--- Listing contents of build/windows ---"
          Get-ChildItem -Path build/windows -ErrorAction SilentlyContinue
        shell: pwsh

      - name: Zip portable build
        run: Compress-Archive -Path build/windows/runner/Release\* -DestinationPath "windows-portable-${{ github.ref_name }}.zip"
        shell: pwsh

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          draft: true
          prerelease: false
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          files: |
            windows-portable-${{ github.ref_name }}.zip