# .github/workflows/windows_release.yml

name: Build & Release Windows App (Portable)

on:
  push:
    tags:
      - 'v*'

jobs:
  build-and-release:
    # --- THIS BLOCK IS NEW ---
    # Grant permissions for the GITHUB_TOKEN to create releases
    permissions:
      contents: write
    # --- END OF NEW BLOCK ---

    runs-on: windows-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        run: flutter pub get

      - name: Build Windows
        run: flutter build windows --release

      - name: Zip portable build
        run: Compress-Archive -Path build/windows/x64/runner/Release\* -DestinationPath "windows-portable-${{ github.ref_name }}.zip"
        shell: pwsh

      - name: Create GitHub Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          # --- THIS LINE IS NEW ---
          # Pass the token that has the 'contents: write' permission
          token: ${{ secrets.GITHUB_TOKEN }}
          
          draft: true
          prerelease: false
          name: ${{ github.ref_name }}
          tag_name: ${{ github.ref }}
          files: |
            windows-portable-${{ github.ref_name }}.zip